--missing dates in the sequence
WITH DATE_LIST AS
(
 SELECT TO_DATE('20.08.2022', 'DD.MM.YYYY') AS D FROM DUAL
 UNION ALL
 SELECT TO_DATE('23.08.2022', 'DD.MM.YYYY') AS D FROM DUAL
 UNION ALL
 SELECT TO_DATE('24.08.2022', 'DD.MM.YYYY') AS D FROM DUAL
 UNION ALL
 SELECT TO_DATE('27.08.2022', 'DD.MM.YYYY') AS D FROM DUAL
 UNION ALL
 SELECT TO_DATE('30.08.2022', 'DD.MM.YYYY') AS D FROM DUAL
)
SELECT (SELECT MIN(TO_DATE(D, 'DD.MM.YYYY')) FROM DATE_LIST) + LEVEL  AS MISSING_DATE
FROM DATE_LIST
CONNECT BY LEVEL <= (SELECT MAX(TO_DATE(D, 'DD.MM.YYYY')) FROM DATE_LIST) - (SELECT MIN(TO_DATE(D, 'DD.MM.YYYY')) FROM DATE_LIST)
MINUS
SELECT  TO_DATE(D, 'DD.MM.YYYY')
FROM DATE_LIST;


